-- MySQL Script generated by MySQL Workbench
-- Wed Apr 21 12:55:23 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema music_store_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema music_store_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `music_store_db` DEFAULT CHARACTER SET utf8 ;
USE `music_store_db` ;

-- -----------------------------------------------------
-- Table `music_store_db`.`countries`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `music_store_db`.`countries` (
  `country_id` INT NOT NULL AUTO_INCREMENT,
  `country_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`country_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `music_store_db`.`provinces`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `music_store_db`.`provinces` (
  `province_id` INT NOT NULL AUTO_INCREMENT,
  `province_name` VARCHAR(45) NOT NULL,
  `country_id` INT NOT NULL,
  PRIMARY KEY (`province_id`),
  INDEX `fk_states_countries1_idx` (`country_id` ASC),
  CONSTRAINT `fk_states_countries1`
    FOREIGN KEY (`country_id`)
    REFERENCES `music_store_db`.`countries` (`country_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `music_store_db`.`cities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `music_store_db`.`cities` (
  `city_id` INT NOT NULL AUTO_INCREMENT,
  `city_name` VARCHAR(45) NOT NULL,
  `province_id` INT NOT NULL,
  PRIMARY KEY (`city_id`),
  INDEX `fk_cities_states1_idx` (`province_id` ASC),
  CONSTRAINT `fk_cities_states1`
    FOREIGN KEY (`province_id`)
    REFERENCES `music_store_db`.`provinces` (`province_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `music_store_db`.`customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `music_store_db`.`customers` (
  `customer_id` INT NOT NULL AUTO_INCREMENT,
  `customer_first_name` VARCHAR(45) NOT NULL,
  `customer_last_name` VARCHAR(45) NOT NULL,
  `customer_phone` VARCHAR(10) NOT NULL,
  `customer_email` VARCHAR(45) NULL,
  `customer_dob` DATE NULL,
  `customer_street_name` VARCHAR(100) NOT NULL,
  `city_id` INT NOT NULL,
  `province_id` INT NOT NULL,
  `country_id` INT NOT NULL,
  `zipcode` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`customer_id`),
  INDEX `fk_customers_cities1_idx` (`city_id` ASC),
  INDEX `fk_customers_states1_idx` (`province_id` ASC),
  INDEX `fk_customers_countries1_idx` (`country_id` ASC),
  CONSTRAINT `fk_customers_cities1`
    FOREIGN KEY (`city_id`)
    REFERENCES `music_store_db`.`cities` (`city_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_customers_states1`
    FOREIGN KEY (`province_id`)
    REFERENCES `music_store_db`.`provinces` (`province_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_customers_countries1`
    FOREIGN KEY (`country_id`)
    REFERENCES `music_store_db`.`countries` (`country_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `music_store_db`.`product_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `music_store_db`.`product_types` (
  `product_type_id` INT NOT NULL AUTO_INCREMENT,
  `product_type_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`product_type_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `music_store_db`.`artists`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `music_store_db`.`artists` (
  `artist_id` INT NOT NULL AUTO_INCREMENT,
  `artist_first_name` VARCHAR(45) NOT NULL,
  `artist_last_name` VARCHAR(45) NULL,
  `artist_description` VARCHAR(200) NULL,
  PRIMARY KEY (`artist_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `music_store_db`.`genres`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `music_store_db`.`genres` (
  `genre_id` INT NOT NULL AUTO_INCREMENT,
  `genre_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`genre_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `music_store_db`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `music_store_db`.`products` (
  `product_id` INT NOT NULL AUTO_INCREMENT,
  `product_name` VARCHAR(45) NOT NULL,
  `product_selling_price` DECIMAL(7,2) NOT NULL DEFAULT 0.00,
  `discount_id` INT NOT NULL,
  `product_type_id` INT NOT NULL,
  `artist_id` INT NOT NULL,
  `product_released_date` DATE NULL,
  `genre_id` INT NOT NULL,
  `stock_in_hand` INT NOT NULL DEFAULT 100,
  PRIMARY KEY (`product_id`),
  INDEX `fk_products_product_types1_idx` (`product_type_id` ASC),
  INDEX `fk_products_artists1_idx` (`artist_id` ASC),
  INDEX `fk_products_genres1_idx` (`genre_id` ASC),
  CONSTRAINT `fk_products_product_types1`
    FOREIGN KEY (`product_type_id`)
    REFERENCES `music_store_db`.`product_types` (`product_type_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_products_artists1`
    FOREIGN KEY (`artist_id`)
    REFERENCES `music_store_db`.`artists` (`artist_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_products_genres1`
    FOREIGN KEY (`genre_id`)
    REFERENCES `music_store_db`.`genres` (`genre_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `music_store_db`.`terms`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `music_store_db`.`terms` (
  `term_id` INT NOT NULL AUTO_INCREMENT,
  `term_description` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`term_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `music_store_db`.`employees`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `music_store_db`.`employees` (
  `employee_id` INT NOT NULL AUTO_INCREMENT,
  `employee_first_name` VARCHAR(45) NOT NULL,
  `employee_last_name` VARCHAR(45) NOT NULL,
  `employee_phone` VARCHAR(10) NOT NULL,
  `employee_dob` DATE NOT NULL,
  `employee_doj` DATE NOT NULL,
  `employee_email` VARCHAR(45) NOT NULL,
  `employee_street_name` VARCHAR(100) NOT NULL,
  `city_id` INT NOT NULL,
  `province_id` INT NOT NULL,
  `country_id` INT NOT NULL,
  `zipcode` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`employee_id`),
  INDEX `fk_employees_cities1_idx` (`city_id` ASC),
  INDEX `fk_employees_provinces1_idx` (`province_id` ASC),
  INDEX `fk_employees_countries1_idx` (`country_id` ASC),
  CONSTRAINT `fk_employees_cities1`
    FOREIGN KEY (`city_id`)
    REFERENCES `music_store_db`.`cities` (`city_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_employees_provinces1`
    FOREIGN KEY (`province_id`)
    REFERENCES `music_store_db`.`provinces` (`province_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_employees_countries1`
    FOREIGN KEY (`country_id`)
    REFERENCES `music_store_db`.`countries` (`country_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `music_store_db`.`invoices`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `music_store_db`.`invoices` (
  `invoice_id` INT NOT NULL AUTO_INCREMENT,
  `invoice_number` VARCHAR(10) NOT NULL,
  `customer_id` INT NOT NULL,
  `invoice_date` DATE NOT NULL DEFAULT now(),
  `invoice_total` DECIMAL(9,2) NOT NULL,
  `invoice_due_date` DATE NOT NULL,
  `term_id` INT NOT NULL,
  `empolyee_id` INT NOT NULL,
  PRIMARY KEY (`invoice_id`),
  UNIQUE INDEX `invoice_number_UNIQUE` (`invoice_number` ASC),
  INDEX `fk_invoices_customers1_idx` (`customer_id` ASC),
  INDEX `fk_invoices_terms1_idx` (`term_id` ASC),
  INDEX `fk_invoices_employees1_idx` (`empolyee_id` ASC),
  CONSTRAINT `fk_invoices_customers1`
    FOREIGN KEY (`customer_id`)
    REFERENCES `music_store_db`.`customers` (`customer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_invoices_terms1`
    FOREIGN KEY (`term_id`)
    REFERENCES `music_store_db`.`terms` (`term_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_invoices_employees1`
    FOREIGN KEY (`empolyee_id`)
    REFERENCES `music_store_db`.`employees` (`employee_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `music_store_db`.`invoice_line_items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `music_store_db`.`invoice_line_items` (
  `line_item_id` INT NOT NULL AUTO_INCREMENT,
  `invoice_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  `quantity` INT NOT NULL,
  `unit_price` DECIMAL(7,2) NOT NULL DEFAULT 0.00,
  `discount_amount` DECIMAL(6,2) NOT NULL DEFAULT 0.00,
  PRIMARY KEY (`line_item_id`),
  INDEX `fk_invoice_line_items_invoices1_idx` (`invoice_id` ASC),
  INDEX `fk_invoice_line_items_products1_idx` (`product_id` ASC),
  CONSTRAINT `fk_invoice_line_items_invoices1`
    FOREIGN KEY (`invoice_id`)
    REFERENCES `music_store_db`.`invoices` (`invoice_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_invoice_line_items_products1`
    FOREIGN KEY (`product_id`)
    REFERENCES `music_store_db`.`products` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `music_store_db`.`discounts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `music_store_db`.`discounts` (
  `discount_id` INT NOT NULL AUTO_INCREMENT,
  `discount_name` VARCHAR(45) NOT NULL,
  `discount_percent` DECIMAL(4,2) NOT NULL DEFAULT 0.00,
  `discount_start_date` DATE NOT NULL,
  `discount_end_date` DATE NOT NULL,
  PRIMARY KEY (`discount_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `music_store_db`.`products_discounts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `music_store_db`.`products_discounts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `product_id` INT NOT NULL,
  `discount_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_products_has_discounts_discounts1_idx` (`discount_id` ASC),
  INDEX `fk_products_has_discounts_products1_idx` (`product_id` ASC),
  CONSTRAINT `fk_products_has_discounts_products1`
    FOREIGN KEY (`product_id`)
    REFERENCES `music_store_db`.`products` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_products_has_discounts_discounts1`
    FOREIGN KEY (`discount_id`)
    REFERENCES `music_store_db`.`discounts` (`discount_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
